### ISSUE TITLE
How to speed up?

### ISSUE THREAD

**Issue by Zergg279** [aDarkDev/Telegram-Seen#2]
Hi, I managed to get it working, which is great, but how do I increase the speed of views? 

I am getting about 100 views every 5 minutes right now - would be great to find out how to increase this speed

**Comment by aDarkDev** [comment]
hi, you can use fast and good proxies, not public proxies.

**Comment by Zergg279** [comment]
Thank you - do you have any recommendations?

**Comment by aDarkDev** [comment]
proxyscrape or others.
