### ISSUE TITLE
.

### ISSUE THREAD

**Issue by TrixSec** [aDarkDev/Telegram-Seen#4]
.

**Comment by aDarkDev** [comment]
what you mean?

**Comment by TrixSec** [comment]
> what you mean?

python seen.py https://t.me/Trixsec/172 http 100
Error . Help : python3 seen.py <link> <type> <count>
Types : http , socks4 , socks5 , mix

**Comment by aDarkDev** [comment]
fixed check latest sources

**Comment by TrixSec** [comment]
> fixed check latest sources

Thanks 😍🫶🏻 ly

**Comment by aDarkDev** [comment]
> > fixed check latest sources
> 
> Thanks 😍🫶🏻 ly

read the readme.md 
good luck
