### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by Tipson** [aDarkDev/Telegram-Seen#5]
Good afternoon, I think there is a problem with the proxy as when I was testing I was getting the response ‘View Sent Stats Code: 200’ but the number of views was not increased.

I am very interested in your development and have a few ideas.

**Comment by aDarkDev** [comment]
Hi sir The process of viewing is such that you get 1 view with each proxy and you cannot view twice with the same proxy. Thank you for your interest.
